#!/bin/bash

for d in dev/dev{1..5}; do
    $d/bin/bigset stop
    $d/bin/bigset start
    $d/bin/bigset ping
done

sleep 10

for d in dev/dev{2..5}; do
    $d/bin/bigset-admin cluster join 'bigset1@127.0.0.1'
done

dev/dev1/bin/bigset-admin cluster plan
dev/dev1/bin/bigset-admin cluster commit

echo "started, pinged, committed, clustering"

while ! dev/dev1/bin/bigset-admin transfers | grep -iqF "No transfers active"
do
    echo "Transfers in Progress"
    sleep 10
done
